# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python
#python:
#    - 3.4

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade nose coverage codecov

install:
    - time sudo apt-get update
    - travis_retry sudo apt-get install gir1.2-pango gir1.2-gtk xdg-utils librsvg2-common libglib2.0-dev intltool
    - travis_retry sudo apt-get install python3-gobject python3-gi python3-cairo python3-gi-cairo python3-bsddb3 python3-dev python3-nose 
    - travis_retry sudo apt-get install python3-mock
    # - travis_retry sudo apt-get install python3-icu

    # - travis_retry sudo pip install pyicu==1.8

    - cd $TRAVIS_BUILD_DIR
    # $TRAVIS_BUILD_DIR is set to the location of the cloned repository:
    # for example: /home/travis/build/gramps-project/gramps
    - python3 setup.py build

#before_script:
#    - sudo Xvfb :99 -ac &
#    - export DISPLAY=:99

script:
    -  mkdir -p ~/.gramps/grampsdb/
    # --exclude=TestUser because of older version of mock
    #                    without configure_mock
    -  nosetests3 --with-coverage --cover-package=gramps --exclude=TestcaseGenerator --exclude=vcard --exclude=merge_ref_test  --exclude=user_test gramps

after_success:
    - codecov

